networks:
  friend-me-network:
    name: friend-me-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      friend-me-network:
        ipv4_address: 10.5.0.5
  friend_me_bot:
    build:
      dockerfile: "Dockerfile"
    ports:
      - "8000:5000"
    environment:
      - BOT_TOKEN
      - AMP_TOKEN=ef58e9e7cdcfabb095f61798d8529d30
      - bot_name=friend_me_bot
      - isDocker=true
      - POSTGRES_HOST=10.5.0.5
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=friend_me_bot
    volumes:
      - ./:/root/app:cached
      - db_volume:/root/db
    networks:
      friend-me-network:
        ipv4_address: 10.5.0.6

volumes: 
    db_volume:
    db_postgres: