name: 'FRIENDME BOT - DEPLOY'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-friend-bot

    steps:
    - uses: actions/checkout@v3
    - name: Environment Var Init
      run: |
        echo "
        BOT_TOKEN: ${{secrets.BOT_TOKEN_MAIN}}" > .env
    - name: Stop FriendMe Bot Container
      run: |
        docker compose stop pay_api_dev
    - name: Deploy FriendMe Bot Container
      run: |
        docker compose up friend_me_bot -d